# See https://pre-commit.com for usage.
minimum_pre_commit_version: "3.5.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: local
    hooks:
      - id: ruff
        name: ruff (lint)
        entry: ruff check --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff (format)
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
