# SPDX-FileCopyrightText: 2026 BreachSAFE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
#
# REUSE bulk annotations for first-party NON-CODE files (docs, ADRs, config, data,
# examples, lockfiles). Source files carry per-file SPDX headers; data/prose files are
# licensed here instead of embedding tags in them. Default precedence ("closest") means a
# file's own header still wins where present -- these entries only fill the gaps.
version = 1

[[annotations]]
path = [
  "**/*.md",
  "**/*.yaml",
  "**/*.yml",
  "**/*.json",
  "**/*.xml",
  "**/*.toml",
  "**/*.ini",
  "**/*.xlsx",
  "**/*.lock",
  "**/.keep",
  ".python-version",
  ".gitignore",
  "NOTICE",
]
SPDX-FileCopyrightText = "2026 BreachSAFE"
SPDX-License-Identifier = "PolyForm-Noncommercial-1.0.0"
